#pragma once
#include "country_codes.dl"

.type VisaType <: symbol
.type PassportType <: symbol
.type Person <: symbol

.decl can_visit_state(person: Person, state: ISO3166_1_alpha_3, basis: symbol, duration: symbol, conditions: symbol)
.decl person_holds_visa(person: Person, state: ISO3166_1_alpha_3, visa_type: VisaType)
.decl person_holds_passport(person: Person, state: ISO3166_1_alpha_3, passport_type: PassportType)
