#include "../country_codes.dl"

.input to_convert
.output country_name_to_iso
.output missing_country_name_to_iso

.decl to_convert(state_name: symbol)

.decl country_name_to_iso(iso: symbol)
country_name_to_iso(iso) :-
    to_convert(name),
    state_iso3_name(iso, name).

.decl missing_country_name_to_iso(name: symbol)
missing_country_name_to_iso(name) :-
    to_convert(name),
    !state_iso3_name(_, name).
